FORMAT: 1A
HOST:http://api.breastcancergenes.com

# Breast Cancer Genes API
Breast Cancer Genes is a simple API allowing consumers to get details about the major suspect genes in breast cancer.

# Group BreastCancerGenes
Access to Breast Cancer Gene data

## My Breast Cancer Genes [/genes]
### Get all of the genes associated with breast cancer [GET]
+ Request

    + Header
    
            Autnorization: Basic ZnJlZXN0dWZm
            
+ Response 200 (application/json)

        {
            "question": "Which breast cancer gene are you interested in?",
            "published_at": "2015-06-20T13:23:51.620Z",
            "url": "/questions/1",
            "choices": [
                {
                    "choice": "BRCA1",
                    "url": "/questions/1/choices/1",
                    "number of base pairs homo sapien": 2048
                }, {
                    "choice": "BRCA2",
                    "url": "/questions/1/choices/2",
                    "number of base pairs homo sapien": 1024
                }, {
                    "choice": "PALB2",
                    "url": "/questions/1/choices/3",
                    "number of base pairs homo sapien": 512
                }, {
                    "choice": "ATM",
                    "url": "/questions/1/choices/4",
                    "number of base pairs homo sapien": 256
                }, {
                    "choice": "RINT1",
                    "url": "questions/1/choices/5",
                    "number of base pairs homo sapien": 3500
                }, {
                    "choice": "MRE11A",
                    "url": "questions/1/choices/5",
                    "number of base pairs homo sapien": 3500
                }, {
                    "choice": "RAD50",
                    "url": "questions/1/choices/5",
                    "number of base pairs homo sapien": 3500
                }, {
                    "choice": "NBN",
                    "url": "questions/1/choices/5",
                    "number of base pairs homo sapien": 3500
                }
            ]
        }
    
        